---
title: "Data preparation"
output: html_notebook
---

# Load required packages 
```{r warning=FALSE}

# Load required packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(stringr, readr, tidyverse, RColorBrewer, ggpubr, dplyr)
```
# Load data
```{r}
source(here::here("code","read_bids.R"))

# Define tasks and their corresponding filenames
tasks <- c("vas", "fastEst", "fastTrl", "psi")
filenames <- c("vas.csv", "fastEst.csv", "fastTrl.csv", "psi.csv")

# Define how to load the data: from the "data" folder in GitHub or from an external folder (eg., cortex)
data_option <- "github" # or "cortex"

# Parameters for the read_bids option
if (data_option == "cortex") {
  projdir <- "/mnt/cortex/bpp/MINDLAB2022_CalibrationTGI" # cortex
  sub <- 1:28     # TO UPDATE BASED ON DATA COLLECTION
  ses <- 1:2
  dat <- "beh"
  save <- TRUE
}

# Initialize an empty list to store the data
data_list <- list()

# Loop through tasks and filenames
for (i in seq_along(tasks)) {
  task <- tasks[i]
  filename <- filenames[i]
  
  if (data_option == "github") {
    # Read data from the data folder in GitHub
    data_list[[task]] <- read.csv(here::here("data", filename), header = TRUE)
  } else if (data_option == "read_bids") {
    data_list[[task]] <- read_bids(projdir, sub, ses, task, dat, save)
  } else {
    stop("Invalid data_option. Please set data_option to either 'github' or 'read_bids'.")
  }
}

# Extract the individual data frames from the list
vas <- data_list[["vas"]]
fe <- data_list[["fastEst"]]
ft <- data_list[["fastTrl"]]
psi <- data_list[["psi"]]
```

# Check data availability
```{r}
# Define the tasks of interest
tasks <- c("vas", "fastEst", "fastTrl", "psi")

# Initialize empty dataframe to store results
df_avail <- data.frame(sub = numeric(), ses = numeric(), stringsAsFactors = FALSE)

# Loop over all tasks
for (task in tasks) {
  
  # Import data for all participants and sessions
  df_task <- data_list[[task]]
  
  # Count number of available files for each participant and session
  avail_counts <- as.data.frame(table(df_task$sub, df_task$ses))
  names(avail_counts) <- c("sub", "ses", task)
  
  # Merge with results dataframe
  df_avail <- merge(df_avail, avail_counts, all = TRUE)
}

# Replace NA values with 0
df_avail[is.na(df_avail)] <- 0

# Print results
print(df_avail)

```
# How many participants did complete the TGI thresholding task?
```{r}
all_sub <- sort(as.numeric(unique(df_avail$sub)))
ses1_df <- df_avail %>% filter(ses == 1 & fastEst == 903)
ses2_df <- df_avail %>% filter(ses == 2 & fastEst == 903)

participants_both_ses <- sort(as.numeric(intersect(ses1_df$sub, ses2_df$sub)))
participant_ses1 <- sort(as.numeric(intersect(all_sub, ses1_df$sub)))
participant_ses2 <- sort(as.numeric(intersect(all_sub, ses2_df$sub)))

# All participants
cat("N = ", length(all_sub), "showed up for the experiment", "\n")
cat("c(", paste0(all_sub, collapse = ", "), ")", "\n")
       
# Session 1
cat("N = ", length(participant_ses1), "completed session 1 of the TGI thresholding task", "\n")
cat("c(", paste0(participant_ses1, collapse = ", "), ")", "\n")

# Session 2
cat("N = ", length(participant_ses2), "completed session 2 of the TGI thresholding task", "\n")
cat("c(", paste0(participant_ses2, collapse = ", "), ")", "\n")

# Session 1 and session 2
cat("N = ", length(participants_both_ses), "completed both sessions of the TGI thresholding task", "\n")
cat("c(", paste0(participants_both_ses, collapse = ", "), ")", "\n")

```

# VAS: Check the number of trials
```{r}
df_summary <- df_avail %>%
  filter(ses %in% c(1,2)) %>%
  group_by(ses) %>%
  summarize(total = length(unique(sub[ses==ses])),
            all_405 = sum(vas == 405), 
            from200_to405 = sum(vas > 200 & vas < 405), 
            from100_to200 = sum(vas > 100 & vas <= 200), 
            none = sum(vas == 0))

df_summary

```
# VAS: summary 
```{r}
# Calculate median of VAS ratings and VAS response times
vas_temps <- vas %>%
  group_by(sub, ses, threshold, gain, stim_type, vas_type) %>%
  summarize(temp_cold = mean(target_cold_t1), temp_warm = mean(target_warm_t1))

vas_ratings <- vas %>%
  group_by(sub, ses, threshold, gain, stim_type, vas_type) %>%
  summarize(vas_rating_median = median(vas_rating), vas_rt_median = median(vas_rt))

df_vas <- inner_join(vas_temps, vas_ratings, by = c('sub', 'ses', 'threshold', 'gain', 'stim_type', 'vas_type'))
df_vas
```
# Thresholds: summary
Define threshold function data and restrict data to TGI range (i.e., all data points below CPT and above HPT are defined as NA)
```{r warning=FALSE}
sublist <- unique(fe$sub)
seslist <- c(1,2)

# Psi thresholds: Select the last row with non-NA data
df_psi <- psi %>%
  group_by(sub, ses, quality) %>%
  filter((quality == "warm" & !is.na(threshold)) | (quality == "cold" & !is.na(threshold))) %>%
  slice(n())
df_psi

# Fast thresholds
df_fe <- crossing(sublist, seslist) %>%
  pmap_dfr(function(sublist, seslist) {
    psi_sub <- df_psi %>% filter(sub == sublist & ses == seslist) # define CPT and HPT for one participant
    cpt <- psi_sub %>% filter(quality == 'cold')
    hpt <- psi_sub %>% filter(quality == 'warm')
    fe_sub <- fe %>% filter(sub == sublist & ses == seslist) # define data for each subject
    fe_sub$temp_cold_na <- fe_sub$temp_cold # copy temp cold_column
    fe_sub$temp_cold_na[fe_sub$temp_cold < cpt$threshold | fe_sub$temp_warm > hpt$threshold] <- NA # remove data below CPT and above HPT
    fe_sub
  })
df_fe


```

# Plot threshold and vas data for each participant
```{r warning=FALSE}
source(here::here('code','plot_sub_v1.R'))

sublist <- unique(fe$sub)

walk(sublist, function(sub_n) {
  thr_plots <- list()
  vas_plots <- list()  
  substr <- paste0('sub-', str_pad(sub_n, 4, pad = '0'))
    
  # Filter data to plot        
  for (seslist in 1:2) {
    # Filter data for a specific participant and session
    vas_sub <- df_vas %>% filter(sub == sub_n & ses == seslist)
    vas_trl <- vas %>% filter(sub == sub_n & ses == seslist)
    fe_sub <- df_fe %>% filter(sub == sub_n & ses == seslist)
    psi_sub <- df_psi %>% filter(sub == sub_n & ses == seslist)
    
    # Set title for the session
    title <- paste(paste('Session', seslist), sep = " ")

    # Plot the session
    thr_plots[[seslist]] <- plot_thr_sub_v1(vas_sub, fe_sub, psi_sub, title)
    vas_plots[[seslist]] <- plot_vas_sub_v1(vas_sub)
  }
  
  # Generate figure combining plots for session 1 and session 2
  g1 <- ggarrange(thr_plots[[1]], thr_plots[[2]], ncol = 2, nrow = 1) #labels = c("A", "B"),
  g1_with_title <- annotate_figure(g1, top = text_grob(paste("TGI thresholds:", substr), size = 14, face = "bold"))
  
  g2 <- ggarrange(vas_plots[[1]], vas_plots[[2]], ncol = 2, nrow = 1)
  
  g <- ggarrange(g1, g2, ncol = 1, nrow = 2)

  # Save figure
  filepath <- here::here('figs', paste0(substr, '.pdf'))
  ggsave(g, file = filepath, width = 20, height = 20, dpi = 100, units = "cm")
})
```

